---
services:
  inference-gateway-ui:
    build:
      context: ../../..
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ../../..:/app
    env_file:
      - .env.ui
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.3"
        reservations:
          memory: 256M
          cpus: "0.15"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - frontend

  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    pull_policy: always
    env_file:
      - .env.gateway
    environment:
      APP_ENVIRONMENT: production
      LOG_LEVEL: warn
      SERVER_READ_TIMEOUT: 130s
      SERVER_WRITE_TIMEOUT: 130s
      SERVER_IDLE_TIMEOUT: 120s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - backend

  google-calendar-agent:
    image: ghcr.io/inference-gateway/google-calendar-agent:latest
    pull_policy: always
    env_file:
      - .env.agent
    environment:
      APP_ENVIRONMENT: production
      LOG_LEVEL: warn
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.3"
        reservations:
          memory: 256M
          cpus: "0.15"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - backend

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    environment:
      A2A_AGENT_URL: http://google-calendar-agent:8080
      LOG_LEVEL: debug
    depends_on:
      - google-calendar-agent
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
