apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-gateway-ui.fullname" . }}
  labels:
    {{- include "inference-gateway-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "inference-gateway-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-defaults.yaml") . | sha256sum }}
        {{- if .Values.envFrom.configMapRef.name }}
        checksum/config-overrides: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if eq .Values.envFrom.configMapRef.name (include "inference-gateway-ui.fullname" .) }}
        checksum/manual-config: {{ printf "%s" (lookup "v1" "ConfigMap" .Release.Namespace (include "inference-gateway-ui.fullname" .)).data | sha256sum }}
        {{- end }}
        {{- if .Values.envFrom.secretRef.name }}
        checksum/secrets-overrides: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if eq .Values.envFrom.secretRef.name (include "inference-gateway-ui.fullname" .) }}
        checksum/manual-secret: {{ printf "%s" (lookup "v1" "Secret" .Release.Namespace (include "inference-gateway-ui.fullname" .)).data | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "inference-gateway-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inference-gateway-ui.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "inference-gateway-ui.fullname" . }}-defaults
            {{- if .Values.envFrom.configMapRef.name }}
            - configMapRef:
                name: {{ .Values.envFrom.configMapRef.name }}
            {{- end }}
            {{- if .Values.envFrom.secretRef.name }}
            - secretRef:
                name: {{ .Values.envFrom.secretRef.name }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
