{{- if .Values.envFrom.secretRef.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFrom.secretRef.name }}
  labels:
    {{- include "inference-gateway-ui.labels" . | nindent 4 }}
stringData:
  # The salt for encypting the JWT token. Read more here: https://next-auth.js.org/configuration/options#nextauth_url
  NEXTAUTH_SECRET: "very-secret-change-me"
  AUTH_OIDC_CLIENT_ID: ""
  AUTH_OIDC_CLIENT_SECRET: ""
  AUTH_OIDC_ISSUER: ""
{{- end }}
