---
services:
  ui:
    image: ghcr.io/inference-gateway/ui:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    depends_on:
      inference-gateway:
        condition: service_started
      keycloak:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "2.5"
          memory: 1512M
        reservations:
          cpus: "0.25"
          memory: 256M
    pull_policy: always
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - app-network

  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    env_file:
      - .env.backend
    depends_on:
      keycloak:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 100M
    pull_policy: always
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command:
      - start-dev
      - --import-realm
      - --verbose
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_LOG_LEVEL: info
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    depends_on:
      keycloak-db:
        condition: service_started
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-config", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  keycloak-db-data:

networks:
  app-network:
    driver: bridge
