name: Artifacts

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  containers:
    name: Build and Push Container Images
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}-${{ matrix.arch }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.arch }}
            type=sha,format=long,suffix=-${{ matrix.arch }}
            type=raw,value=latest-${{ matrix.arch }},enable=${{ !contains(github.ref, '-rc') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create_manifest:
    name: Create Multi-Architecture Manifest
    runs-on: ubuntu-24.04
    needs: containers
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for manifest
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
            type=raw,value=latest,enable=${{ !contains(github.ref, '-rc') }}

      - name: Create and push manifest
        run: |
          set -e

          export DOCKER_CLI_EXPERIMENTAL=enabled

          echo "Creating manifests for tags: ${{ steps.meta.outputs.tags }}"
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' '); do
            echo "Creating manifest for: $tag"
            echo "  - amd64 image: $tag-amd64"
            echo "  - arm64 image: $tag-arm64"
            
            echo "Checking if images exist..."
            if ! docker manifest inspect $tag-amd64 > /dev/null 2>&1; then
              echo "Error: $tag-amd64 not found"
              exit 1
            fi
            if ! docker manifest inspect $tag-arm64 > /dev/null 2>&1; then
              echo "Error: $tag-arm64 not found"
              exit 1
            fi
            
            echo "Creating manifest..."
            docker manifest create $tag \
              $tag-amd64 \
              $tag-arm64
            
            echo "Pushing manifest..."
            docker manifest push $tag
          done

  sign_containers:
    name: Sign Container Images
    runs-on: ubuntu-24.04
    needs: create_manifest
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: "v2.4.3"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata from previous job
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
            type=raw,value=latest,enable=${{ !contains(github.ref, '-rc') }}

      - name: Sign container image
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' '); do
            cosign sign --yes $tag
          done

  charts:
    name: Publish Helm Chart
    runs-on: ubuntu-24.04
    needs: create_manifest
    env:
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.17.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Helm chart
        run: |
          VERSION=${TAG#v}
          cd charts/inference-gateway-ui
          helm dependency update
          helm package . --version ${VERSION} --app-version ${VERSION}
          helm push inference-gateway-ui-${VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
